version: "3"
services:
  nginx:
    restart: "always"
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "3002:80"
  postgres:
    image: "postgres:latest"
  redis-server:
    image: "redis:latest"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
  api:
    build:
       context: ./server
       dockerfile: Dockerfile.dev
    volumes:
       - /app/node_modules
       - ./server:/app
    environment:
        - REDIS_HOST=redis-server
        - REDIS_PORT=6379
        - PGUSER=postgres
        - PGHOST=postgres
        - PGDATABASE=postgres
        - PGPASSWORD=postgres_password
        - PGPORT=5432
  worker:
    build:
       context: ./worker
       dockerfile: Dockerfile.dev
    volumes:
       - /app/node_modules
       - ./worker:/app
    environment:
        - REDIS_HOST=redis-server
        - REDIS_PORT=6379
